#!/usr/bin/env python
# -*- coding: ascii -*-

# Copyright 2006-2012
# Andr\xe9 Malo or his licensors, as applicable.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
usage: wtfctl <options>
"""
import os
import sys
import traceback

from wtf import cmdline, config

try:
    cmdline.run()

except cmdline.CommandlineError, e:
    msg = str(e)
    if msg:
        print >> sys.stderr, str(e)
    print >>sys.stderr, "Try %s --help for usage information" % \
        os.path.basename(sys.argv[0])
    sys.exit(2)

except config.ConfigurationError, e:
    print >> sys.stderr, "Configuration Error: %s\n" % str(e)
    print >> sys.stderr, '-' * 78
    traceback.print_exc(file=sys.stderr)
    sys.exit(1)
